appNet:
  signMessages: false
  encryptMessages: false
  rotateKeys: false
  rotateKeyFrequency: 0
  topics:
    - topic: 0.0.1004
  persistenceLevel: "FULL"

queue:
  tcpConnectionFactory: "tcp://hcsqueue:61616"
    
HCSTransactionFee: 100000000

nodes:
  - address: 35.222.103.151:50211
    account: 0.0.3
# Commented out due to bug in java SDK
#  - address: 1.testnet.hedera.com:50211
#    account: 0.0.4
#  - address: 2.testnet.hedera.com:50211
#    account: 0.0.5
#  - address: 3.testnet.hedera.com:50211
#    account: 0.0.6